[WIP] Updated subscription code
maticzav/swift-graphql pull request #74
Opened 2022-03-23 09:17 UTC by terhechte

2022-03-24 08:14 UTC, Amzd requested changes

2022-03-24 08:14 UTC, Amzd commented on Sources/SwiftGraphQL/HTTP+WebSockets.swift
> +        case data
You changed the protocol. I can't find it now but we had a discussion originally which protocol to support and we decided the `graphql-transport-ws` https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md 

You still set that protocol in the header so the server will reply with the original message types.

2022-03-31 15:17 UTC, maticzav commented
@terhechte, thank you for coming up with this. I am truly grateful for the work, the timing just seems to be super bad because I am about to release v3.0.0 of SwiftGraphQL (#70) that's going to handle GraphQLWebSockets a bit differently. I'll surely use your code as inspiration though.

2022-04-06 06:25 UTC, terhechte commented
@maticzav No problem :) We needed these right now, so doing them was still useful from my perspective. Once 3.0 is rolled out, I suppose we will gladly switch over :)

One thing I didn't do in the PR but that I think would make sense is to have a configuration option for either subscriptions-transport-was or graphql-ws so that it works with both transports. Some servers support both protocols in a backwards-compatible way, but some only support one. The difference between the two protocols is also pretty marginal.

2022-07-23 07:58 UTC, maticzav commented
@terhechte would you recommend using `os_log` in favour of [`swift-log`](https://github.com/apple/swift-log.git)? I see that you used `os_log` and hoped that you could explain the difference.

2022-08-03 15:43 UTC, maticzav commented
With the release of the new version, I am closing this PR. It has been of great value. Feel free to reopen it if you think this could still benefit the new client, and I'll happily check it out.

2022-08-03 15:43 UTC, closed without merging